name: Python application

on:
  push:
    branches : [crawler]

  schedule:
  - cron: 0 7 * * * 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: crawling
      env:
        AWS_RDS_DB: ${{secrets.AWS_RDS_DB}}
        AWS_RDS_HOST: ${{secrets.AWS_RDS_HOST}}
        AWS_RDS_PASSWD: ${{secrets.AWS_RDS_PASSWD}}
        AWS_RDS_PORT: ${{secrets.AWS_RDS_PORT}}
        AWS_RDS_USER: ${{secrets.AWS_RDS_USER}}
      run: |
        python3 musinsa_dbconnector.py